---

- include_vars: remove_user.yml

- name: Remove the user in vars/remove_user.yml file
  user:
    name: "{{ item.name }}"
    state: absent
    remove: yes
  with_items: " {{ remove_users }}"
  when: remove_users is defined
