---
language: python
python: "3.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python3-pip

install:
  # Install requirements
  - pip3 install -r requirements.txt

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=ansible/roles' >ansible.cfg

script:
  # Syntax check roles.
  - cd ansible && make test_all 

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
