---
# vars file for install_apt_packages
apt_package_list:
  - python-apt
  - sudo
  - lftp
  - htop
  - dnsutils
  - netcat
  - iotop
  - ntp
  - bash-completion
  - git
  - curl
  - wget
  - bzip2
  - unzip
  - net-tools
  - python-pip
  - python3-pip
