---

- name: Create site on /etc/nginx/sites-available/
  template:
    src: normal_site.conf.j2
    dest: /etc/nginx/sites-available/{{ servername }}

- name: Create symlink on /etc/nginx/sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ servername }}
    dest: /etc/nginx/sites-enabled/{{ servername }}
    owner: "{{ nginx_user }}"
    state: link

- name: Restart nginx service
  service:
    name: nginx
    state: reloaded
