---
# tasks file for webproxy

- import_tasks: install_nginx.yml
  tags:
    - nginx
  when: install_nginx_opt == 'yes'

- import_tasks: apply_config.yml
  tags:
    - nginx
    - config
  when: apply_config_opt == 'yes'

- import_tasks: create_site.yml
  tags:
    - nginx
    - create_site
  when: create_site_opt == 'yes'

- import_tasks: install_certbot.yml
  tags:
    - certbot
    - install
  when: install_certbot_opt == 'yes'

- import_tasks: create_ssl_cert.yml
  tags:
    - certbot
    - create-ssl
  when: create_ssl_cert_opt == 'yes'