---

users:
  - name: mario
    uid: 1100
    password: 
    comment: User mario must be on every server.
    home: yes
    update_password: on_create
    generate_ssh_key: yes
    shell: /bin/bash
    groups: 
      - sudo
      - www-data 
    user_state: present
  
  - name: victor
    uid: 1101
    password:
    comment: User victor
    home: yes
    update_password: on_create
    generate_ssh_key: yes
    shell: /bin/bash
    groups:
      - sudo
    user_state: present
