---
# tasks file for hetzner

- import_tasks: activate_rescue.yml
  tags:
    - hetzner 
    - activate_rescue 
  when: activate_rescue_opt == 'yes'

- import_tasks: install_image.yml
  tags:
    - hetzner 
    - install_image 
  when: install_image_opt == 'yes'