---
# tasks file for galera

- import_tasks: pre_tasks.yml
  tags:
    - pretasks
    - galera 
  when: pre_tasks_opt == "yes"

- import_tasks: install_mariadb.yml
  tags:
    - install 
    - mariadb
  when: install_mariadb_opt == "yes"

- import_tasks: configure_galera.yml
  tags:
    - configure
    - galera
  when: configure_galera_opt == "yes"