---

- include_vars: install_proxmox.yml

- name: Add the apt Proxmox repository key
  apt_key:
    url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    state: present

- name: Add an apt Proxmox repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
    state: present

- name: Install Proxmox packages 
  apt:
    name: "{{ proxmox_packages_list }}"
    state: present
    update_cache: yes
  when: proxmox_packages_list is defined   

- name: Remove proxmox enterprise repository
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise
    state: absent