# Task to add the node to a existing Proxmox cluster

---

# Add node to cluster

- name: Check that there is no cluster on the server
  stat:
    path: /etc/pve/corosync.conf
  register: stat_result

- name: Add node to the cluster
  shell:
    cmd: "pvecm add {{ master_ip }} -use_ssh"
  when: not stat_result.stat.exists
