---

- name: Set hostname
  hostname:
    name: "{{ vm_hostname }}"
  when: vm_hostname is defined

  # 57
- name: Modify /etc/hosts
  template:
    src: hosts_file.sh.j2
    dest: /etc/hosts

- name: Remove old SSH keys
  file:
    path: "/home/{{ host_user }}/.ssh/{{item }}"
    state: absent
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Create SSH keys
  openssh_keypair:
    path: "/home/{{ host_user }}/.ssh/id_rsa"
    force: True

- name: Install recommended packages
  apt:
    name: "{{ recommended_packages }}"
    state: present
  when: recommended_packages is defined 

- name: PermitRootLogin yes
  become_user: root
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin prohibit-password'
    line: PermitRootLogin yes

- name: Set mtu 1400 to interfaces
  become: yes 
  command: >-
    ip link set mtu 1400 dev "{{ interface }}"
  when: interface is defined

- name: Restart ssh service 
  become_user: root
  service:
    name: sshd
    state: restarted

    