---

# This role is responsible for:
# # 1. Configure /etc/network/interfaces

- include_vars: configure_node.yml

- name: Change /etc/network/interfaces using template
  template:
    src: interfaces.sh.j2
    dest: /etc/network/interfaces
  notify: Reboot

- name: Create thin lvm storage
  lvol:
    vg: vg00
    thinpool: thin
    size: "{{ thinsize }}" 
  when: thinsize is defined
  ignore_errors: yes

- name: Extend meta data size of thin
  command: >-
    lvextend --poolmetadatasize 6G vg00/thin
  when: thinsize is defined
  ignore_errors: yes

  #- name: Create thin lvm storage
  #  command: >-
  #    lvcreate -L "{{ thinsize }}" --thinpool vg00/thin
  #  when: thinsize is defined
  #
  #- name: Extend meta data size of thin
  #  command: >-
  #    lvextend --poolmetadatasize 6G vg00/thin
  #  when: thinsize is defined

  #- name: Add thin to datacenter
  #  command: >-
  #    pvesm add lvmthin

  #- name: Restart server after network configuration
  #  reboot:
  #    msg: "Reboot by Ansible"
  #
  #- name: Wait till server up
  #  wait_for:
  #    port: 22 
  #    delay: 10


