---

- include_vars: create_cluster.yml

# Create a Proxmox cluster
- name: Create cluster
  block:
    - name: Check if cluster exists
      shell:
        cmd: "pvecm status"
      register: pvecm_status
  rescue:
    - name: If there is no cluster, create one
      command: >- 
        pvecm create {{ clustername }}
        {% if link0 is defined %}
        {{ link0_flag }} {{ link0 }}
        {% endif %}
        {% if link1 is defined %}
        {{ link1_flag }} {{ link1 }}
        {% endif %}

