---

# Create VM on Proxmox VE
# Vars:
# create_vm.name
# create_vm.vmid
# create_vm.memory
# create_vm.sockets
# create_vm.cores
# create_vm.bridge{n}
# create_vm.iso_name
# create_vm.disk_size
#
# node:
#
# OPT: create_vm_opt: 'yes'
#

- include_vars: create_vm.yml
- include_vars: secrets.yml

- name: Check if VM alredy exists with same ID
  stat:
    path: "/var/lib/vz/images/{{ create_vm.vmid }}"
  register: vm_exists

- name: Debug
  debug:
    msg: "Alredy exists on VM with that ID"
  when: vm_exists.stat.exists

- name: Create VM on proxmox with pvesh cli
  shell:
    cmd: "pvesh create /nodes/{{ node }}/qemu 
          -name {{ create_vm.name }} 
          -vmid {{ create_vm.vmid }}
          -memory {{ create_vm.memory }}
          -cpu host
          -socket {{ create_vm.sockets }}
          -cores {{ create_vm.cores }}
          -cdrom {{ template }}
          -scsi0 local-lvm:{{ create_vm.disk_size }}
          -net0 virtio,bridge={{ create_vm.bridge }}
          {% if create_vm.bridge1 is defined %}
          -net1 virtio,bridge={{ create_vm.bridge1 }}
          {% endif %}
          {% if create_vm.bridge2 is defined %}
          -net2 virtio,bridge={{ create_vm.bridge2 }}
          {% endif %}
          {% if create_vm.bridge3 is defined %}
          -net3 virtio,bridge={{ create_vm.bridge3 }}
          {% endif %}"
