--- 

- name: Download master pub key
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: /tmp/
    flat: yes
  delegate_to: "{{ master_ip }}" 

- name: Add master key to authorized_keys
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/tmp/id_rsa.pub' }}"
    
- name: Delete id_rsa.pub
  file:
    path: /tmp/id_rsa.pub
    state: absent
  delegate_to: 127.0.0.1

- name: Download host pub key
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: /tmp/
    flat: yes

- name: Add host key to master authorized_keys
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/tmp/id_rsa.pub' }}"
  delegate_to: "{{ master_ip }}" 

- name: Delete id_rsa.pub
  file:
    path: /tmp/id_rsa.pub
    state: absent
  delegate_to: 127.0.0.1
