---
# defaults file for proxmox

# Options:
install_proxmox_opt: 'no'
create_vm_opt: 'no'
upload_iso_opt: 'no'
pfsense_conf_opt: 'no'
create_cluster_opt: 'no'
add_to_cluster_opt: 'no'
manage_users_opt: 'no'
remove_cluster_opt: 'no'
manage_groups_opt: 'no'


# Upload iso role defauls
proxmox:
  user: foo
  password: foopw

  node: tfg
  storage: local
  iso_url: foo
  iso_name: debian
  host: tfg.intelligenia.com

# Defaults for create_vm role
create_vm:
  vmid: 100
  host: tfg.intelligenia.com
  password: "{{ proxmox.password }}"
  hostname: intelligenia.test
  ostemplate: 'local:_22pfSense-CE-2.4.5_22.iso'


# Defaults for pfsense_conf_opt
ppal_iface: enp0s31f6
hetzner_ip: 138.201.205.158
hetzner_gateway: 138.201.205.129
hetzner_broadcast: 138.201.205.191
pfsense_ip_node1: 255.255.255.255
pfsense_ip_node2: 255.255.255.255
failover_ip: 255.255.255.255
node_proxmox_ip: 192.168.100.1
vlan_nodes_id: 1
vlan_lan_id: 1
vlan_pfsync_id: 1
vlan_nodes2_id: 1

# Defaults for install_proxmox
# There is no optional vars for install_proxmox role

# Defaults for create_cluster
clustername: tfgcluster


# Defaults for task deploy_pub_key
master_ip: tfg.intelligenia.com
