FROM python:3.6
ENV PYTHONUNBUFFERED 1

RUN apt update && apt install -y gettext

COPY ./src/requirements/base.txt /base.txt
RUN pip install -r base.txt

WORKDIR /code

COPY ./compose/entrypoint /entrypoint
RUN sed -i 's/\r//' /entrypoint
RUN chmod +x /entrypoint

COPY ./compose/start /start
RUN sed -i 's/\r//' /start
RUN chmod +x /start

ENTRYPOINT ["/entrypoint"]
