---

# this will execute on all nodes of cluster.
- name: Create privileged user k8_ansible
  user:
    name: "{{ k8_ansible_user }}"
    append: yes
    state: present
    create_home: yes
    shell: /bin/bash

- name: Allow k8_ansible to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: '"{{ k8_ansible_user }}" ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set up authorized key for user k8_ansible copying it from current user
  authorized_key:
    user: "{{ k8_ansible_user }}"
    state: present
    key: "{{ lookup('file', '/home/{{ id_rsa_user }}/.ssh/id_rsa.pub') }}"
  
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: Add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Install kubelet
  apt:
    name: kubelet=1.18.6-00
    state: present
    install_recommends: yes
    update_cache: true

- name: Install kubeadm
  apt:
    name: kubeadm=1.18.6-00
    install_recommends: yes
    state: present