- hosts: ceph-all
  gather_facts: no
  become: yes

  # Pendiente cambiar /etc/hosts 
  # chown -R {{ host_user }}:{{ host_user }} /home/mario/.ssh
  vars:
    interface: ens18
    host_user: mario
    recommended_packages:
      - net-tools
      - htop
      - nmap
      - ncdu
      - netcat
      - curl
      - wget
      - vim 
      - ntp
     
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ ceph_hostname }}"
      when: ceph_hostname is defined

    - name: Remove old SSH keys
      file:
        path: "/home/{{ host_user }}/.ssh/{{item }}"
        state: absent
      with_items:
        - id_rsa
        - id_rsa.pub
    
    - name: Create SSH keys
      openssh_keypair:
        path: "/home/{{ host_user }}/.ssh/id_rsa"
        force: True

    - name: Set authorized keys, removing all previous 
      authorized_key:
        user: "{{ host_user }}"
        state: present
        exclusive: True
        key: "{{ item }}"
      with_file:
        - public_keys/mario
        - public_keys/victor-oficina
        - public_keys/victor-pc
        - public_keys/victor-portatil

    - name: Install recommended packages
      apt:
        name: "{{ recommended_packages }}"
        state: present

    - name: PermitRootLogin yes
      become_user: root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin prohibit-password'
        line: PermitRootLogin yes

    - name: Restart ssh service 
      become_user: root
      service:
        name: sshd
        state: restarted

    - name: Set mtu 1400 to interfaces
      command: >-
        sudo ip link set mtu 1400 dev "{{ interface }}"
     
       
- hosts: tfg-ceph-admin
  gather_facts: no
  become: yes

  vars:
    host_user: mario
    first_node_ip: 10.6.100.30

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
        install_recommends: yes

    - name: Install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present
        install_recommends: yes

    - name: Add CEPH apt-key
      apt_key:
        url: https://download.ceph.com/keys/release.asc
        state: present

    - name: Add ceph apt repository
      apt_repository:
        repo: deb https://download.ceph.com/debian-octopus buster main

    - name: Download cephadm
      get_url:
        url: https://downloads-tfg.intelligenia.com/cephadm
        dest: /usr/local/bin
        mode: '0755'

    - name: Create ceph directory
      file:
        path: /etc/ceph
        state: directory
        mode: 0755

    - name: Initialize ceph cluster with 1 node
      become_user: root
      command: >-
        cephadm bootstrap --mon-ip {{ first_node_ip }}

    - name: Install ceph common packages with cephadm 
      become_user: root
      command: >-
        cephadm install ceph-common

    - name: Get public key of tfg-ceph-admin
      become_user: "{{ host_user }}"
      shell: cat $HOME/.ssh/id_rsa.pub
      register: id_rsa_pub

    - name: Get public key of ceph cluster
      become_user: root
      shell: cat /etc/ceph/ceph.pub
      register: ceph_pub
      
    - name: Set facts id_rsa_pub
      set_fact:
        ssh_pub_key: "{{ id_rsa_pub.stdout }}"

    - name: Set facts ceph key
      set_fact:
        ssh_ceph_pub_key: "{{ ceph_pub.stdout }}"

- hosts: ceph-nodes
  gather_facts: no
  become: yes

  vars:
    host_user: mario

  tasks:
    - name: Add id_rsa_pub of tfg-ceph-admin to authorized_keys
      become_user: "{{ host_user }}"
      authorized_key:
        user: "{{ host_user }}"
        state: present
        key: "{{ hostvars['tfg-ceph-admin'].ssh_pub_key }}"

    - name: Add id_rsa_pub of tfg-ceph-admin to authorized_keys
      become_user: root
      authorized_key:
        user: root
        state: present
        key: "{{ hostvars['tfg-ceph-admin'].ssh_pub_key }}"

    - name: Add id_rsa_pub of ceph cluster to authorized_keys
      become_user: root
      authorized_key:
        user: root
        state: present
        key: "{{ hostvars['tfg-ceph-admin'].ssh_ceph_pub_key }}"
    
 #- hosts: tfg-ceph-admin
 # gather_facts: no
 # become: yes
 # become_user: root
#
 # vars:
 #   ceph_workers:
 #     - tfg-ceph-node-01
 #     - tfg-ceph-node-02
 #     - tfg-ceph-node-03
#
 # tasks:
 #   # Passwords, vault encrypted file
 #   - include_vars: secrets.yml
#
 #   - name: Add nodes to ceph cluster
 #     become_user: root 
 #     command: >-
 #         ceph orch host add {{ item }}
 #     with_items: "{{ ceph_workers }}"
#
 #   - name: Create user for ceph dashboard
 #     command: >-
 #       sudo ceph dashboard ac-user-create {{ ceph_dashboard_admin }} {{ ceph_dashboard_admin_password }} administrator
#
 #   - name: Tell ceph to dont automatic deploy monitors, we choose them
 #     command: >-
 #       ceph orch apply mon --unmanaged
 #   
 #   - name: Tell ceph to only deploy 4 mons, we only have 4 nodes. 
 #     command: >-
 #       ceph orch apply mon 4
#
 #   - name: Add labels to nodes, mon, osd, mgr 
 #     shell: |
 #       ceph orch host label add ceph-node-01 osd
 #       ceph orch host label add ceph-node-02 osd 
 #       ceph orch host label add ceph-node-03 osd 
 #       ceph orch host label add ceph-node-03 mgr 
 #       ceph orch host label add tfg-ceph-admin mgr 
 #       ceph orch host label add ceph-node-01 mds
 #       ceph orch host label add ceph-node-02 mds
 #       ceph orch host label add ceph-node-01 mon
 #       ceph orch host label add ceph-node-02 mon 
 #       ceph orch host label add ceph-node-03 mon 
 #       ceph orch host label add tfg-ceph-admin mon
 #           
#
#