---

# This playbook is responsible for:
# 1. Install essential packages on server.
# 2. Configure network interfaces
# 3. Add bash users.


- hosts: tfg.intelligenia.com
  gather_facts: false
  become: yes


  vars:
    # Vars for manage_package 
    #remove_apt_repository_opt: 'yes'
    #add_apt_repository_opt: 'yes'
    install_apt_packages_opt: 'yes'
    install_pip_packages_opt: 'yes'
    #upgrade_packages_repository_opt: 'yes'

    # Proxmox role add task or not.
    pfsense_conf_opt: 'yes'
    #manage_groups_opt: 'yes'
    #manage_users_opt: 'yes'
    #add_firewall_rule_opt: 'yes'

    # Proxmox users / groups
    #create_groups_opt: 'yes'

    create_user_bash_opt: 'yes'

    apt_package_list:
      #- python-apt
      #- python3-apt
      - python-pip
      - python3-pip
      - sudo
      #- lftp
      #- htop
      - dnsutils
      #- netcat
      #- iotop
      - ntp
      #- bash-completion
      - git
      - curl
      - wget
      #- bzip2
      #- unzip
      - net-tools
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common

      #- proxmox-ve
      #- postfix
      #- open-iscsi

        #pip_package_list:
        #  - proxmoxer
        #  - requests


    #key_url_list: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    #remove_apt_repo: deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise
    #add_repo_list:
    #  - deb http://download.proxmox.com/debian/pve buster pve-no-subscription

  roles:
    - manage_users
    - manage_packages
    #- proxmox
