---
 
- hosts: pfsense_master

  # Must have non-password ssh access
  # # ssh-copy-id root@tfg-pfsense-01.intelligenia.com -p 11000

  gather_facts: no
  tags: create_dhcp_pfsense

  vars:
    pfsense_config_path: /cf/conf/config.xml
    pfsense_ssh_port: 11000
    pfsense_configure_dhcp_opt: 'yes'
    
    vms_to_configure:
      - name: ceph-admin
        vm_mac: 4E:55:60:E5:C9:C8
        vm_id: 310
        vm_ip: 10.6.100.30
        vm_hostname: ceph-admin
        vm_domain: tfg.vps

      - name: ceph-node-01
        vm_mac: 62:92:8B:2D:B9:E1
        vm_id: 311
        vm_ip: 10.6.100.31
        vm_hostname: ceph-node-01
        vm_domain: tfg.vps

      - name: ceph-node-02
        vm_mac: DE:49:69:28:9A:DA
        vm_id: 312
        vm_ip: 10.6.100.32
        vm_hostname: ceph-node-02
        vm_domain: tfg.vps

      - name: ceph-node-03
        vm_mac: 92:69:02:CA:1C:95
        vm_id: 313
        vm_ip: 10.6.100.33
        vm_hostname: ceph-node-03
        vm_domain: tfg.vps

  roles:
    - pfsense

- hosts: proxmox_master
  gather_facts: false
  tags: create_vm

  vars:
    create_vm_opt: 'yes'
    start_after_create: 'yes'

    interface: ens18
    host_user: mario

    downloads:
      - name: Debian 10 Template
        download_url: https://downloads-tfg.intelligenia.com/vzdump-qemu-878-2020_07_20-08_29_27.vma.zst
        backup_destination: /var/lib/vz/dump/vzdump-qemu-878-2020_07_18-22_44_27.vma.zst

    create_vms:
      - name: ceph-node-01
        backup_location: /var/lib/vz/dump/vzdump-qemu-878-2020_07_18-22_44_27.vma.zst
        kvm_name: ceph-node-01
        kvm_cores: 2
        kvm_memory: 1024
        kvm_mac: 62:92:8B:2D:B9:E1
        kvm_sockets: 2
        new_id: 311
        start_at_boot: "yes"
      - name: ceph-admin
        backup_location: /var/lib/vz/dump/vzdump-qemu-878-2020_07_18-22_44_27.vma.zst
        kvm_name: ceph-admin
        kvm_cores: 2 
        kvm_memory: 2048
        kvm_mac: 4E:55:60:E5:C9:C8
        kvm_sockets: 2
        new_id: 310
        start_at_boot: "yes"

    create_disk_opt: "yes"
    vm_id: 311
    disk_size: 10
      
  roles:
    - proxmox_kvm

- hosts: proxmox_slave
  gather_facts: false
  tags: create_vm

  vars:
    create_vm_opt: 'yes'
    start_after_create: 'yes'
    interface: ens18
    host_user: mario

    downloads:
      - name: Debian 10 Template
        download_url: https://downloads-tfg.intelligenia.com/vzdump-qemu-878-2020_07_20-08_29_27.vma.zst
        backup_destination: /var/lib/vz/dump/vzdump-qemu-878-2020_07_18-22_44_27.vma.zst

    create_vms:
      - name: ceph-node-02
        backup_location: /var/lib/vz/dump/vzdump-qemu-878-2020_07_18-22_44_27.vma.zst
        kvm_name: ceph-node-02
        kvm_cores: 2 
        kvm_memory: 1024
        kvm_mac: DE:49:69:28:9A:DA
        kvm_sockets: 1
        new_id: 312
        start_at_boot: "yes"

    create_disk_opt: "yes"
    vm_id: 312
    disk_size: 10
      
  roles:
    - proxmox_kvm

- hosts: tfg3.intelligenia.com
  gather_facts: false
  tags: create_vm

  vars:
    create_vm_opt: 'yes'
    start_after_create: 'yes'

    interface: ens18
    host_user: mario

    downloads:
      - name: Debian 10 Template
        download_url: https://downloads-tfg.intelligenia.com/vzdump-qemu-878-2020_07_20-08_29_27.vma.zst
        backup_destination: /var/lib/vz/dump/vzdump-qemu-878-2020_07_18-22_44_27.vma.zst

    create_vms:
      - name: ceph-node-03
        backup_location: /var/lib/vz/dump/vzdump-qemu-878-2020_07_18-22_44_27.vma.zst
        kvm_name: ceph-node-03
        kvm_cores: 2 
        kvm_memory: 1024
        kvm_mac: 92:69:02:CA:1C:95
        kvm_sockets: 1
        new_id: 313
        start_at_boot: "yes"
    
    create_disk_opt: "yes"
    vm_id: 313
    disk_size: 10

  roles:
    - proxmox_kvm

  post_tasks:
    - name: Wait 60 seconds to Vms to come up
      wait_for:
        timeout: 60 

- hosts: ceph
  tags: ceph-configure-common 
  gather_facts: no
  become: yes

  vars:
    configure_vm_opt: 'yes'
    vm_domain: tfg.vps

    interface: ens18
    host_user: mario

    recommended_packages:
      - net-tools
      - htop
      - nmap
      - ncdu
      - netcat
      - curl
      - wget
      - vim 
      - ntp
      - apt-transport-https
      - ca-certificates 
      - software-properties-common
      - tcpdump 
      - openssl
      - python
      - gnupg

  roles:
    - proxmox_kvm

- hosts: pfsense_master
  gather_facts: no 
  tags: restart_pfsense

  vars:
    pfsense_ssh_port: 11000

  tasks:
    - name: Change ssh port to {{ pfsense_ssh_port }}
      set_fact:
        ansible_port: "{{ pfsense_ssh_port }}"

    - name: Delete cache file in order to make changes persistent
      file:
        state: absent
        path: /tmp/config.cache

    - name: Restart dhcp service on pfsense
      command: >-
        pfSsh.php playback svc restart dhcpd

- hosts: ceph
  become: yes
  gather_facts: no
  tags: ceph_create_cluster

  vars:
    add_nodes_to_cluster_opt: "yes"
    install_docker_opt: "yes"
    deploy_ceph_keys_opt: "yes"
    install_ceph_opt: "yes"
    create_cluster_opt: "yes"

    configure_dashboard_access_opt: "yes" 
    deploy_ceph_mons_opt: "yes"
    deploy_ceph_osd_opt: "yes"
    deploy_ceph_mgr_opt: "yes"
    deploy_ceph_mds_opt: "yes"
    create_cephfs_opt: "yes"

    ceph_dashboard_admin: victortest 
    ceph_dashboard_admin_password: dummypassword

    osd_disk_path_1: /dev/sdb
    osd_disk_path_2: /dev/sdb
    osd_disk_path_3: /dev/sdb

    host_user: mario
    first_node_ip: 10.6.100.30

    ceph_workers:
      - ceph-node-01
      - ceph-node-02
      - ceph-node-03

  pre_tasks:
    - name: Try to ping ceph nodes 
      block:
      - name: Try to ping ceph nodes, sometimes DNS fails
        shell: ping {{ item }}.tfg.vps
        register: task_result
        until: task_result.rc == 0
        retries: 10
        delay: 2
        ignore_errors: yes
        with_items: ceph_workers
      
      rescue:
      - name: If fails ask user to restart pfsense DHCP server
        debug:
          msg: "Go to pfsense interface, and restart DHCP server"
        
  roles:
    - ceph