- hosts: proxmox_slave
  gather_facts: false

  vars:
    configure_vm_opt: 'no'
    create_vm_opt: 'yes'
    firewall_pfsense_conf: 'yes'

    downloads:
        - name: PfSense-02 Template
          download_url: https://downloads-tfg.intelligenia.com/vzdump-qemu-998-2020_07_17-09_28_06.vma.zst
          backup_destination: /var/lib/vz/dump/vzdump-qemu-998-2020_07_17-09_28_06.vma.zst

    create_vms:
        - name: pfSense-02
          backup_location: /var/lib/vz/dump/vzdump-qemu-998-2020_07_17-09_28_06.vma.zst
          kvm_name: tfg-pfsense-02
          kvm_cores: 2 
          kvm_memory: 2048
          kvm_mac: 00:50:56:00:9C:A2 # MUST BE THA MAC REQUESTES ON HETZNER SECONDARY IP.
          kvm_sockets: 2
          new_id: 998
          start_at_boot: "yes"

  roles:
    - proxmox_kvm

- hosts: proxmox_master
  gather_facts: false
  
  vars:
    configure_vm_opt: 'no'
    create_vm_opt: 'yes'
    firewall_pfsense_conf: 'yes'
  
    downloads:
        - name: PfSense-01 Template
          download_url: https://downloads-tfg.intelligenia.com/vzdump-qemu-999-2020_07_17-09_27_15.vma.zst
          backup_destination: /var/lib/vz/dump/vzdump-qemu-999-2020_07_17-09_27_15.vma.zst
    create_vms:
        - name: pfSense-01
          backup_location: /var/lib/vz/dump/vzdump-qemu-999-2020_07_17-09_27_15.vma.zst
          kvm_name: tfg-pfsense-01
          kvm_cores: 2 
          kvm_memory: 1024
          kvm_mac: 00:50:56:00:03:CA # MUST BE THA MAC REQUESTES ON HETZNER SECONDARY IP.
          kvm_sockets: 1
          new_id: 999
          start_at_boot: "yes"
  
  roles:
    - proxmox_kvm

- hosts: localhost
  connection: local

  tasks:
    - include_vars: secrets.yml

    - name: Wait for port 11000 to be open pfsense-01
      wait_for: 
        host: tfg-pfsense-01.intelligenia.com
        port: 11000
        timeout: 120

    - name: Wait for port 11000 to be open pfsense-02
      wait_for: 
        host: tfg-pfsense-02.intelligenia.com
        port: 11000
        timeout: 120

    - name: SSH copy id to pfsense-01
      expect:
        command: ssh-copy-id -o StrictHostKeyChecking=no root@tfg-pfsense-01.intelligenia.com -p 11000
        responses: 
          (?i)password: "{{ ssh_pfsense01_password }}"

    - name: SSH copy id to pfsense-02
      expect:
        command: ssh-copy-id -o StrictHostKeyChecking=no root@tfg-pfsense-02.intelligenia.com -p 11000
        responses: 
          (?i)password: "{{ ssh_pfsense02_password }}"

# ssh-copy-id root@tfg-pfsense-01.intelligenia.com -p 11000
# ssh-copy-id root@tfg-pfsense-02.intelligenia.com -p 11000

- hosts: pfsense_master
  gather_facts: no

  # There's no need to add multiple vms to dhcp server.
  # When we create the VM, we configure dhcp aswell.
  
  vars:
    pfsense_ssh_port: 11000
    apply_pfsense_config: 'yes'
    pfsense_full_domain: tfg-pfsense-01.intelligenia.com
    pfsense_hostname: tfg-pfsense-01
    pfsense_hostname2: intelligenia.vps
    pfsense_gateway: 10.6.0.3
    pfsense_dns: 10.6.0.3
    pfsense_slave: 10.6.0.2
    pfsense_master: 10.6.0.1
    pfsense_carp: 10.6.0.3
    pfsense_wui_domain: intelligenia.com
    pfsense_domain: tfg.vps
    pfsense_wui_port: 8443
    pfsense_update_bogons: monthly
    pfsense_timezone: Etc/UTC
    dns_list:
      - name: Google 1
        ip: 1.1.1.1
      - name: Google 2
        ip: 8.8.8.8
      - name: Google 3
        ip: 8.8.4.4 
    pfsense_wan_ip_address: 138.201.229.85
    pfsense_wan_subnet: 29
    pfsense_wan_gateway_name: WANGW
    pfsense_wan_gateway_ip: 138.201.229.81
    pfsense_lan_ip_address: 10.6.0.1
    pfsense_lan_subnet: 16
    pfsense_lan_gateway_ip: 10.6.0.3
    pfsense_lan_gateway_name: CARP_MASTER   
    pfsense_failover_ip_address: 144.76.47.196
    pfsense_failover_subnet: 32
    pfsense_failover_gateway_name: FAILOVER_GW
    pfsense_failover_gateway_ip: 138.201.205.158    
    pfsense_pfsync_ip_address: 192.168.1.1
    pfsense_pfsync_peer_ip_address: 192.168.1.2
    pfsense_pfsync_subnet: 24

    # Secrets
    #
    # pfSense admin WUI 
    #pfsense_wui_user: admin
    #pfsense_wui_password: tfg-intellicluster..

  pre_tasks:
    - include_vars: secrets.yml

  roles:
    - pfsense