---

- hosts: tfg2.intelligenia.com
  gather_facts: false

  vars:
    # Proxmox role add task or not.
    pfsense_conf_opt: 'yes'
    manage_groups_opt: 'yes'
    manage_users_opt: 'yes'
    add_firewall_rule_opt: 'yes'

    # Proxmox users / groups
    create_groups_opt: 'yes'

  roles:
    #- install_proxmox
    - proxmox
