---

- name: Download install script
  get_url:
    url: http://software.virtualmin.com/gpl/scripts/install.sh
    dest: /tmp/install.sh

- name: Give execution permission to file
  file:
    dest: /tmp/install.sh
    mode: a+x

- name: Execute installation script
  shell: /tmp/install.sh
  register: output