---

- name: First add the apt repository key
  apt_key:
    url: "{{ key_url_list }}" 
    state: present
  when: key_url_list is defined

- name: Add an apt repository
  apt_repository:
    repo: "{{ item }}" 
    state: present
  with_items: "{{ add_repo_list }}"
  when: add_repo_list is defined
  
