---
# tasks file for install_apt_packages

- include_vars: apt_package_list.yml

- name: Print apt_package_list variable
  debug:
    msg: "{{ apt_package_list }}"
  tags: debug_info

- name: Install apt packages defined on vars/install_apt_packages_vars.yml file
  apt:
    pkg: "{{ apt_package_list }}"
    #state: present
    #update_cache: yes
  when: apt_package_list is defined
