---
# tasks file for manage_packages

- name: First, check if any package needs to be reconfigured
  command: >-
    dpkg --configure -a

- import_tasks: add_apt_repository.yml
  tags:
    - system
    - apt
    - add-repo

- import_tasks: remove_apt_repository.yml
  tags:
    - system
    - apt
    - remove-repo

      #- import_tasks: update_apt_cache.yml
      #  tags:
      #    - system
      #    - update-cache 
      #    - apt 

- import_tasks: add_apt_sources_list.yml
  tags:
    - system
    - apt
    - mirror
    
#- import_tasks: upgrade_all_packages.yml
#  tags:
#    - system
#    - upgrade-packages 
#    - apt 

- import_tasks: install_apt_packages.yml
  tags:
    - system
    - install-packages 
    - apt 

- import_tasks: install_pip_packages.yml
  tags:
    - system
    - install-packages
    - pip 

