---

- include_vars: remove_apt_packages.yml

- name: Remove apt packages defined on vars/remove_apt_packages_vars.yml
  apt:
    name: "{{ items }}"
    state: absent
  with_items: "{{ remove_apt_packages }}"
  when: remove_apt_packages is defined
