# Boot into Rescue
# http://wiki.hetzner.de/index.php/Robot_Webservice#Boot-Konfiguration
# http://wiki.hetzner.de/index.php/Robot_Webservice#Reset

- name: Comprobar que el servidor está en modo rescue 
  shell: hostname
  register: is_rescue_hostname
  failed_when: is_rescue_hostname.stdout.find('rescue') == -1

- name: Creamos fichero temporal para alojar el script de instalación 
  shell: mktemp --tmpdir tmp.XXXXXXXXXX.sh
  register: tmp_file
  when: is_rescue_hostname.stdout.find('rescue') != -1

- name: Copiamos el script de instalación 
  template:
    src: install.sh.j2
    dest: "{{tmp_file.stdout}}"
    mode: 0700
  when: is_rescue_hostname.stdout.find('rescue') != -1

- name: Ejecutamos el script de instalación 
  shell: "{{tmp_file.stdout}}"
  when: is_rescue_hostname.stdout.find('rescue') != -1
  
- name: Reiniciar después de la instalación
  reboot:
