# Boot into Rescue
# http://wiki.hetzner.de/index.php/Robot_Webservice#Boot-Konfiguration
# http://wiki.hetzner.de/index.php/Robot_Webservice#Reset

- name: Check that the server is on rescue mode 
  shell: hostname
  register: is_rescue_hostname
  failed_when: is_rescue_hostname.stdout.find('rescue') == -1

- name: Reboot after Rescue mode activation.
  reboot:

- name: Create temp file to copy the installation script
  shell: mktemp --tmpdir tmp.XXXXXXXXXX.sh
  register: tmp_file

- name: Copy installation script
  template:
    src: install.sh.j2
    dest: "{{tmp_file.stdout}}"
    mode: 0700

- name: Execute installation script
  shell: "{{tmp_file.stdout}}"
  
- name: Reboot after installation 
  reboot:
