---

- name: Check if there is one swarm created
  shell: docker node ls
  register: swarm_created
  ignore_errors: true
  no_log: True
  tags: docker-swarm

- name: Initialize Docker Swarm
  shell: >
        docker swarm init
        --advertise-addr={{ docker_swarm_manager_ip }}:2377
  when: swarm_created.rc != 0
  run_once: true
  tags: docker-swarm

- name: Get docker join token 
  shell: >-
    docker swarm join-token --quiet manager
  register: manager_token
  tags: docker-swarm

- name: Get worker join token 
  shell: >-
    docker swarm join-token --quiet worker
  register: worker_token
  tags: docker-swarm