---

- name: First restart the server in case Rescue mode is enabled wrongly
  uri:
    url: "{{ hetzner.hardware_reset_url }}"
    method: POST
    user: "{{ hetzner.user }}"
    password: "{{ hetzner.password }}"
    body_format: form-urlencoded
    body:
      type: hw
  

- name: Wait 30s and continue with play
  wait_for:
    timeout: 30

- name: Activate Rescue mode if is not activated 
  uri: 
    url: "{{ hetzner.rescue_url }}"
    method: POST
    user: "{{ hetzner.user }}"
    password: "{{ hetzner.password }}"
    body_format: form-urlencoded
    body:
      os: linux
      arch: 64
      authorized_key: "{{ hetzner.fingerprint }}"
 
- name: Reboot server after Rescue Mode activation
  uri:
    url: "{{ hetzner.hardware_reset_url }}"
    method: POST
    user: "{{ hetzner.user }}"
    password: "{{ hetzner.password }}"
    body_format: form-urlencoded
    body:
      type: hw

- name: Wait for server to be ready
  wait_for:
    port: 22 
    host: "{{ server_ip }}" 
    connect_timeout: 20
    delay: 20
    timeout: 500
