---

host: tfg.intelligenia.com

# install_image vars
disks:
  - nvme0n1
  - nvme1n1 


# node tfg values role proxmox task configure_node
ppal_iface: enp0s31f6
hetzner_ip: 138.201.205.158 # tfg2 144.76.2.146 #tfg1 138.201.205.158
hetzner_gateway: 138.201.205.129 # tfg2 144.76.2.129 #tfg 138.201.205.129
hetzner_broadcast: 138.201.205.191 # tfg2 144.76.2.159 # tfg 138.201.205.191
pfsense_ip_node: 138.201.229.85 # tfg2 144.76.2.118 # tfg 138.201.229.85
failover_ip: 144.76.47.196 # tfg2 144.76.47.196
node_proxmox_ip: 192.168.100.1 # tfg2 192.168.100.2


# Proxmox vars
create_cluster_opt: 'yes'
node: tfg
clustername: tfgcluster

# Firewall rules to add
add_rule:
  - name: Port mapper block
    node: tfg
    action: DROP
    type: in
    dport: 111
    proto: tcp
  - name: Accept all traffic on LAN
    node: tfg
    type: group
    action: allowall
    interface: vbmr2
  - name: Accept all traffic on Proxmox nodes
    node: tfg
    type: group
    action: allowall
    interface: vbmr1


target: tfg.intelligenia.com
hostname: tfg.intelligenia.com
