---

host: tfg.intelligenia.com
hostname: tfg.intelligenia.com

# install_image vars
disks:
  - nvme0n1
  - nvme1n1 

# node tfg values role proxmox task configure_node
ppal_iface: enp0s31f6
hetzner_ip: 138.201.205.158 
hetzner_gateway: 138.201.205.129 
hetzner_broadcast: 138.201.205.191 
pfsense_ip_node: 138.201.229.85 
failover_ip: 144.76.47.196 
node_proxmox_ip: 192.168.100.1 
node_redundant_corosync_ip: 192.168.200.1
thinsize: 300G

# Vars for create cluster
# Only on master add create_cluster_opt

create_cluster_opt: "yes"
link0_flag: "--link0"
link1_flag: "--link1"
link0: 192.168.100.1
link1: 192.168.200.1
clustername: tfgcluster

master: 'yes' # Master of proxmox cluster 
pfsense_conf_opt: 'yes' # Create additional pfSense NIC
node: tfg 