---

host: tfg.intelligenia.com

# install_image vars
disks:
  - nvme0n1
  - nvme1n1 


# node tfg values role proxmox task configure_node
ppal_iface: enp0s31f6
hetzner_ip: 138.201.205.158 # tfg2 144.76.2.146 #tfg1 138.201.205.158
hetzner_gateway: 138.201.205.129 # tfg2 144.76.2.129 #tfg 138.201.205.129
hetzner_broadcast: 138.201.205.191 # tfg2 144.76.2.159 # tfg 138.201.205.191
pfsense_ip_node: 138.201.229.85 # tfg2 144.76.2.118 # tfg 138.201.229.85
failover_ip: 144.76.47.196 # tfg2 144.76.47.196
node_proxmox_ip: 192.168.100.1 # tfg2 192.168.100.2
node_redundant_corosync_ip: 192.168.200.1


# Proxmox vars Mover las variables al playobok
create_cluster_opt: 'yes'
node: tfg
clustername: tfgcluster
master: 'yes'

# Firewall rules to add
add_rule:
  - name: Port mapper block
    node: tfg
    action: DROP
    type: in
    dport: 111
    proto: tcp
  - name: Accept all traffic on LAN
    node: tfg
    type: group
    action: allowall
    interface: vbmr2
  - name: Accept all traffic on Proxmox nodes
    node: tfg
    type: group
    action: allowall
    interface: vbmr1

target: tfg.intelligenia.com
hostname: tfg.intelligenia.com

#downloads:
#  - name: Debian 10 Template
#    download_url: https://downloads-tfg.intelligenia.com/vzdump-qemu-802-2020_06_29-03_47_32.vma.lzo
#    backup_destination: /var/lib/vz/dump/vzdump-qemu-802-2020_06_29-03_47_32.vma.lzo
#
#  - name: PfSense-01 Backup
#    download_url: https://downloads-tfg.intelligenia.com/vzdump-qemu-999-2020_07_17-09_27_15.vma.zst
#    backup_destination: /var/lib/vz/dump/vzdump-qemu-999-2020_07_17-09_27_15.vma.zst
#
#create_vms:
#  - name: PfSense-01
#    backup_location: /var/lib/vz/dump/vzdump-qemu-999-2020_07_17-09_27_15.vma.zst
#    new_id: 999
#
#  - name: GitLab
#    backup_location: /var/lib/vz/dump/vzdump-qemu-802-2020_06_29-03_47_32.vma.lzo
#    new_id: 101
#
#  - name: WebProxy
#    backup_location: /var/lib/vz/dump/vzdump-qemu-802-2020_06_29-03_47_32.vma.lzo
#    new_id: 102
#
#  - name: Docker Swarm 01
#    backup_location: /var/lib/vz/dump/vzdump-qemu-802-2020_06_29-03_47_32.vma.lzo
#    new_id: 103
#
#  - name: Ceph Admin
#    backup_location: /var/lib/vz/dump/vzdump-qemu-802-2020_06_29-03_47_32.vma.lzo
#    new_id: 106
#
#  - name: Ceph Node 03
#    backup_location: /var/lib/vz/dump/vzdump-qemu-802-2020_06_29-03_47_32.vma.lzo
#    new_id: 109